/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminProductRouteImport } from './routes/admin/product'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAdminRouteImport } from './routes/admin/admin'
import { Route as AuthTermsRouteImport } from './routes/Auth/terms'
import { Route as AuthSignupRouteImport } from './routes/Auth/signup'
import { Route as AuthSigninRouteImport } from './routes/Auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/Auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/Auth/forgot-password'
import { Route as AuthEmailCheckRouteImport } from './routes/Auth/email-check'
import { Route as AuthEmailRouteImport } from './routes/Auth/email'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductRoute = AdminProductRouteImport.update({
  id: '/admin/product',
  path: '/admin/product',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/admin',
  path: '/admin/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTermsRoute = AuthTermsRouteImport.update({
  id: '/Auth/terms',
  path: '/Auth/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/Auth/signup',
  path: '/Auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/Auth/signin',
  path: '/Auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/Auth/reset-password',
  path: '/Auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/Auth/forgot-password',
  path: '/Auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailCheckRoute = AuthEmailCheckRouteImport.update({
  id: '/Auth/email-check',
  path: '/Auth/email-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailRoute = AuthEmailRouteImport.update({
  id: '/Auth/email',
  path: '/Auth/email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Auth/email': typeof AuthEmailRoute
  '/Auth/email-check': typeof AuthEmailCheckRoute
  '/Auth/forgot-password': typeof AuthForgotPasswordRoute
  '/Auth/reset-password': typeof AuthResetPasswordRoute
  '/Auth/signin': typeof AuthSigninRoute
  '/Auth/signup': typeof AuthSignupRoute
  '/Auth/terms': typeof AuthTermsRoute
  '/admin/admin': typeof AdminAdminRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/product': typeof AdminProductRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Auth/email': typeof AuthEmailRoute
  '/Auth/email-check': typeof AuthEmailCheckRoute
  '/Auth/forgot-password': typeof AuthForgotPasswordRoute
  '/Auth/reset-password': typeof AuthResetPasswordRoute
  '/Auth/signin': typeof AuthSigninRoute
  '/Auth/signup': typeof AuthSignupRoute
  '/Auth/terms': typeof AuthTermsRoute
  '/admin/admin': typeof AdminAdminRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/product': typeof AdminProductRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Auth/email': typeof AuthEmailRoute
  '/Auth/email-check': typeof AuthEmailCheckRoute
  '/Auth/forgot-password': typeof AuthForgotPasswordRoute
  '/Auth/reset-password': typeof AuthResetPasswordRoute
  '/Auth/signin': typeof AuthSigninRoute
  '/Auth/signup': typeof AuthSignupRoute
  '/Auth/terms': typeof AuthTermsRoute
  '/admin/admin': typeof AdminAdminRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/product': typeof AdminProductRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Auth/email'
    | '/Auth/email-check'
    | '/Auth/forgot-password'
    | '/Auth/reset-password'
    | '/Auth/signin'
    | '/Auth/signup'
    | '/Auth/terms'
    | '/admin/admin'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/product'
    | '/admin/profile'
    | '/admin/settings'
    | '/app/dashboard'
    | '/app'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Auth/email'
    | '/Auth/email-check'
    | '/Auth/forgot-password'
    | '/Auth/reset-password'
    | '/Auth/signin'
    | '/Auth/signup'
    | '/Auth/terms'
    | '/admin/admin'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/product'
    | '/admin/profile'
    | '/admin/settings'
    | '/app/dashboard'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/Auth/email'
    | '/Auth/email-check'
    | '/Auth/forgot-password'
    | '/Auth/reset-password'
    | '/Auth/signin'
    | '/Auth/signup'
    | '/Auth/terms'
    | '/admin/admin'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/product'
    | '/admin/profile'
    | '/admin/settings'
    | '/app/dashboard'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthEmailRoute: typeof AuthEmailRoute
  AuthEmailCheckRoute: typeof AuthEmailCheckRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthTermsRoute: typeof AuthTermsRoute
  AdminAdminRoute: typeof AdminAdminRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductRoute: typeof AdminProductRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/product': {
      id: '/admin/product'
      path: '/admin/product'
      fullPath: '/admin/product'
      preLoaderRoute: typeof AdminProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admin': {
      id: '/admin/admin'
      path: '/admin/admin'
      fullPath: '/admin/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth/terms': {
      id: '/Auth/terms'
      path: '/Auth/terms'
      fullPath: '/Auth/terms'
      preLoaderRoute: typeof AuthTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth/signup': {
      id: '/Auth/signup'
      path: '/Auth/signup'
      fullPath: '/Auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth/signin': {
      id: '/Auth/signin'
      path: '/Auth/signin'
      fullPath: '/Auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth/reset-password': {
      id: '/Auth/reset-password'
      path: '/Auth/reset-password'
      fullPath: '/Auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth/forgot-password': {
      id: '/Auth/forgot-password'
      path: '/Auth/forgot-password'
      fullPath: '/Auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth/email-check': {
      id: '/Auth/email-check'
      path: '/Auth/email-check'
      fullPath: '/Auth/email-check'
      preLoaderRoute: typeof AuthEmailCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth/email': {
      id: '/Auth/email'
      path: '/Auth/email'
      fullPath: '/Auth/email'
      preLoaderRoute: typeof AuthEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthEmailRoute: AuthEmailRoute,
  AuthEmailCheckRoute: AuthEmailCheckRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthTermsRoute: AuthTermsRoute,
  AdminAdminRoute: AdminAdminRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductRoute: AdminProductRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
